insert into public.gift_categories (name, sort_order) values
  ('Fralda P', 1),
  ('Fralda M', 2),
  ('Fralda G', 3)
on conflict (name) do update set sort_order = excluded.sort_order;

insert into public.event_settings (
  baby_name,
  event_title,
  event_date,
  event_time,
  address,
  address_reference,
  google_maps_url,
  google_maps_embed_url,
  pix_key,
  pix_receiver_name,
  pix_city,
  pix_bank,
  invitation_message,
  final_message
)
select
  'Liara',
  'Cha de Bebe da Liara',
  '2026-08-02',
  '14:00',
  'Rua Santiago, 236 - Serrinha, Fortaleza - CE',
  'Espaço de eventos Felix',
  'https://maps.app.goo.gl/8xsQsqPHuxQkFhiS7',
  'https://www.google.com/maps?q=Rua+Santiago+236+Serrinha+Fortaleza+CE&output=embed',
  '075.650.053-20',
  'Tiala Debora Fernandes Nobre',
  'Fortaleza',
  'Santander',
  'Com muito amor, estamos preparando a chegada da nossa pequena Liara e gostariamos de compartilhar esse momento especial com voce.',
  'Obrigada por fazer parte desse momento tao especial.'
where not exists (select 1 from public.event_settings);

with categories as (
  select id, name from public.gift_categories
)
insert into public.gifts (seed_code, category_id, name, estimated_value, suggested_brands, status, sort_order)
values
  ('P1', (select id from categories where name = 'Fralda P'), 'Fralda P + Lenço Umedecido Huggies', 70, 'Pampers Confort Sec, Huggies Tripla Protecao ou MamyPoko', 'available', 1),
  ('P2', (select id from categories where name = 'Fralda P'), 'Fralda P + Lenço Umedecido Huggies', 70, 'Pampers Confort Sec, Huggies Tripla Protecao ou MamyPoko', 'available', 2),
  ('P3', (select id from categories where name = 'Fralda P'), 'Fralda P + Lenço Umedecido Huggies', 70, 'Pampers Confort Sec, Huggies Tripla Protecao ou MamyPoko', 'available', 3),
  ('P4', (select id from categories where name = 'Fralda P'), 'Fralda P + Lenço Umedecido Huggies', 70, 'Pampers Confort Sec, Huggies Tripla Protecao ou MamyPoko', 'available', 4),
  ('P5', (select id from categories where name = 'Fralda P'), 'Fralda P + Pomada Bepantriz Baby', 80, 'Pampers Confort Sec, Huggies Tripla Protecao ou MamyPoko', 'available', 5),
  ('P6', (select id from categories where name = 'Fralda P'), 'Fralda P + Pomada Bepantriz Baby', 80, 'Pampers Confort Sec, Huggies Tripla Protecao ou MamyPoko', 'available', 6),
  ('P7', (select id from categories where name = 'Fralda P'), 'Fralda P + Pomada Bepantriz Baby', 80, 'Pampers Confort Sec, Huggies Tripla Protecao ou MamyPoko', 'available', 7),
  ('P8', (select id from categories where name = 'Fralda P'), 'Fralda P + Pomada Bepantriz Baby', 80, 'Pampers Confort Sec, Huggies Tripla Protecao ou MamyPoko', 'available', 8),
  ('P9', (select id from categories where name = 'Fralda P'), 'Fralda P + Sabonete Líquido Natura Mamãe e Bebê', 95, 'Pampers Confort Sec, Huggies Tripla Protecao ou MamyPoko', 'available', 9),
  ('P10', (select id from categories where name = 'Fralda P'), 'Fralda P + Sabonete Líquido Natura Mamãe e Bebê', 95, 'Pampers Confort Sec, Huggies Tripla Protecao ou MamyPoko', 'available', 10),
  ('P11', (select id from categories where name = 'Fralda P'), 'Fralda P + Shampoo Baby Dove', 80, 'Pampers Confort Sec, Huggies Tripla Protecao ou MamyPoko', 'available', 11),
  ('P12', (select id from categories where name = 'Fralda P'), 'Fralda P + Shampoo Baby Dove', 80, 'Pampers Confort Sec, Huggies Tripla Protecao ou MamyPoko', 'available', 12),
  ('P13', (select id from categories where name = 'Fralda P'), 'Fralda P + Condicionador Baby Dove', 80, 'Pampers Confort Sec, Huggies Tripla Protecao ou MamyPoko', 'available', 13),
  ('P14', (select id from categories where name = 'Fralda P'), 'Fralda P + Condicionador Baby Dove', 80, 'Pampers Confort Sec, Huggies Tripla Protecao ou MamyPoko', 'available', 14),
  ('P15', (select id from categories where name = 'Fralda P'), 'Fralda P + Colônia Natura Mamãe e Bebê', 120, 'Pampers Confort Sec, Huggies Tripla Protecao ou MamyPoko', 'available', 15),
  ('P16', (select id from categories where name = 'Fralda P'), 'Fralda P + Colônia Natura Mamãe e Bebê', 120, 'Pampers Confort Sec, Huggies Tripla Protecao ou MamyPoko', 'available', 16),
  ('P17', (select id from categories where name = 'Fralda P'), 'Fralda P + Algodão Cremer', 65, 'Pampers Confort Sec, Huggies Tripla Protecao ou MamyPoko', 'available', 17),
  ('P18', (select id from categories where name = 'Fralda P'), 'Fralda P + Algodão Cremer', 65, 'Pampers Confort Sec, Huggies Tripla Protecao ou MamyPoko', 'available', 18),
  ('P19', (select id from categories where name = 'Fralda P'), 'Fralda P + Cotonetes Johnson''s Baby', 65, 'Pampers Confort Sec, Huggies Tripla Protecao ou MamyPoko', 'available', 19),
  ('P20', (select id from categories where name = 'Fralda P'), 'Fralda P + Cotonetes Johnson''s Baby', 65, 'Pampers Confort Sec, Huggies Tripla Protecao ou MamyPoko', 'available', 20),
  ('P21', (select id from categories where name = 'Fralda P'), 'Fralda P + Prendedor de Chupeta Buba', 80, 'Pampers Confort Sec, Huggies Tripla Protecao ou MamyPoko', 'available', 21),
  ('P22', (select id from categories where name = 'Fralda P'), 'Fralda P + Prendedor de Chupeta Buba', 80, 'Pampers Confort Sec, Huggies Tripla Protecao ou MamyPoko', 'available', 22),
  ('P23', (select id from categories where name = 'Fralda P'), 'Fralda P + Mimo', 90, 'Pampers Confort Sec, Huggies Tripla Protecao ou MamyPoko', 'available', 23),
  ('P24', (select id from categories where name = 'Fralda P'), 'Fralda P + Mimo', 90, 'Pampers Confort Sec, Huggies Tripla Protecao ou MamyPoko', 'available', 24),
  ('P25', (select id from categories where name = 'Fralda P'), 'Fralda P + Mimo', 90, 'Pampers Confort Sec, Huggies Tripla Protecao ou MamyPoko', 'available', 25),
  ('P26', (select id from categories where name = 'Fralda P'), 'Fralda P + Mimo', 90, 'Pampers Confort Sec, Huggies Tripla Protecao ou MamyPoko', 'available', 26),
  ('P27', (select id from categories where name = 'Fralda P'), 'Fralda P + Lenço Umedecido Huggies', 70, 'Pampers Confort Sec, Huggies Tripla Protecao ou MamyPoko', 'available', 27),
  ('P28', (select id from categories where name = 'Fralda P'), 'Fralda P + Pomada Bepantriz Baby', 80, 'Pampers Confort Sec, Huggies Tripla Protecao ou MamyPoko', 'available', 28),
  ('P29', (select id from categories where name = 'Fralda P'), 'Fralda P + Shampoo Baby Dove', 80, 'Pampers Confort Sec, Huggies Tripla Protecao ou MamyPoko', 'available', 29),
  ('P30', (select id from categories where name = 'Fralda P'), 'Fralda P + Condicionador Baby Dove', 80, 'Pampers Confort Sec, Huggies Tripla Protecao ou MamyPoko', 'available', 30),
  ('P31', (select id from categories where name = 'Fralda P'), 'Fralda P + Colônia Natura Mamãe e Bebê', 120, 'Pampers Confort Sec, Huggies Tripla Protecao ou MamyPoko', 'available', 31),
  ('P32', (select id from categories where name = 'Fralda P'), 'Fralda P + Algodão Cremer', 65, 'Pampers Confort Sec, Huggies Tripla Protecao ou MamyPoko', 'available', 32),
  ('P33', (select id from categories where name = 'Fralda P'), 'Fralda P + Cotonetes Johnson''s Baby', 65, 'Pampers Confort Sec, Huggies Tripla Protecao ou MamyPoko', 'available', 33),
  ('P34', (select id from categories where name = 'Fralda P'), 'Fralda P + Lenço Umedecido Huggies', 70, 'Pampers Confort Sec, Huggies Tripla Protecao ou MamyPoko', 'available', 34),
  ('P35', (select id from categories where name = 'Fralda P'), 'Fralda P + Pomada Bepantriz Baby', 80, 'Pampers Confort Sec, Huggies Tripla Protecao ou MamyPoko', 'available', 35),
  ('P36', (select id from categories where name = 'Fralda P'), 'Fralda P + Shampoo Baby Dove', 80, 'Pampers Confort Sec, Huggies Tripla Protecao ou MamyPoko', 'available', 36),
  ('P37', (select id from categories where name = 'Fralda P'), 'Fralda P + Condicionador Baby Dove', 80, 'Pampers Confort Sec, Huggies Tripla Protecao ou MamyPoko', 'available', 37),
  ('P38', (select id from categories where name = 'Fralda P'), 'Fralda P + Prendedor de Chupeta Buba', 80, 'Pampers Confort Sec, Huggies Tripla Protecao ou MamyPoko', 'available', 38),
  ('P39', (select id from categories where name = 'Fralda P'), 'Fralda P + Mimo', 90, 'Pampers Confort Sec, Huggies Tripla Protecao ou MamyPoko', 'available', 39),
  ('P40', (select id from categories where name = 'Fralda P'), 'Fralda P + Mimo', 90, 'Pampers Confort Sec, Huggies Tripla Protecao ou MamyPoko', 'available', 40),
  ('M1', (select id from categories where name = 'Fralda M'), 'Fralda M + Lenço Umedecido Huggies', 75, 'Pampers Confort Sec, Huggies Tripla Protecao ou MamyPoko', 'available', 41),
  ('M2', (select id from categories where name = 'Fralda M'), 'Fralda M + Lenço Umedecido Huggies', 75, 'Pampers Confort Sec, Huggies Tripla Protecao ou MamyPoko', 'available', 42),
  ('M3', (select id from categories where name = 'Fralda M'), 'Fralda M + Lenço Umedecido Huggies', 75, 'Pampers Confort Sec, Huggies Tripla Protecao ou MamyPoko', 'available', 43),
  ('M4', (select id from categories where name = 'Fralda M'), 'Fralda M + Lenço Umedecido Huggies', 75, 'Pampers Confort Sec, Huggies Tripla Protecao ou MamyPoko', 'available', 44),
  ('M5', (select id from categories where name = 'Fralda M'), 'Fralda M + Lenço Umedecido Huggies', 75, 'Pampers Confort Sec, Huggies Tripla Protecao ou MamyPoko', 'available', 45),
  ('M6', (select id from categories where name = 'Fralda M'), 'Fralda M + Pomada Bepantriz Baby', 85, 'Pampers Confort Sec, Huggies Tripla Protecao ou MamyPoko', 'available', 46),
  ('M7', (select id from categories where name = 'Fralda M'), 'Fralda M + Pomada Bepantriz Baby', 85, 'Pampers Confort Sec, Huggies Tripla Protecao ou MamyPoko', 'available', 47),
  ('M8', (select id from categories where name = 'Fralda M'), 'Fralda M + Pomada Bepantriz Baby', 85, 'Pampers Confort Sec, Huggies Tripla Protecao ou MamyPoko', 'available', 48),
  ('M9', (select id from categories where name = 'Fralda M'), 'Fralda M + Pomada Bepantriz Baby', 85, 'Pampers Confort Sec, Huggies Tripla Protecao ou MamyPoko', 'available', 49),
  ('M10', (select id from categories where name = 'Fralda M'), 'Fralda M + Pomada Bepantriz Baby', 85, 'Pampers Confort Sec, Huggies Tripla Protecao ou MamyPoko', 'available', 50),
  ('M11', (select id from categories where name = 'Fralda M'), 'Fralda M + Sabonete Natura Mamãe e Bebê', 100, 'Pampers Confort Sec, Huggies Tripla Protecao ou MamyPoko', 'available', 51),
  ('M12', (select id from categories where name = 'Fralda M'), 'Fralda M + Sabonete Natura Mamãe e Bebê', 100, 'Pampers Confort Sec, Huggies Tripla Protecao ou MamyPoko', 'available', 52),
  ('M13', (select id from categories where name = 'Fralda M'), 'Fralda M + Sabonete Natura Mamãe e Bebê', 100, 'Pampers Confort Sec, Huggies Tripla Protecao ou MamyPoko', 'available', 53),
  ('M14', (select id from categories where name = 'Fralda M'), 'Fralda M + Shampoo Baby Dove', 85, 'Pampers Confort Sec, Huggies Tripla Protecao ou MamyPoko', 'available', 54),
  ('M15', (select id from categories where name = 'Fralda M'), 'Fralda M + Shampoo Baby Dove', 85, 'Pampers Confort Sec, Huggies Tripla Protecao ou MamyPoko', 'available', 55),
  ('M16', (select id from categories where name = 'Fralda M'), 'Fralda M + Shampoo Baby Dove', 85, 'Pampers Confort Sec, Huggies Tripla Protecao ou MamyPoko', 'available', 56),
  ('M17', (select id from categories where name = 'Fralda M'), 'Fralda M + Shampoo Baby Dove', 85, 'Pampers Confort Sec, Huggies Tripla Protecao ou MamyPoko', 'available', 57),
  ('M18', (select id from categories where name = 'Fralda M'), 'Fralda M + Condicionador Baby Dove', 85, 'Pampers Confort Sec, Huggies Tripla Protecao ou MamyPoko', 'available', 58),
  ('M19', (select id from categories where name = 'Fralda M'), 'Fralda M + Condicionador Baby Dove', 85, 'Pampers Confort Sec, Huggies Tripla Protecao ou MamyPoko', 'available', 59),
  ('M20', (select id from categories where name = 'Fralda M'), 'Fralda M + Condicionador Baby Dove', 85, 'Pampers Confort Sec, Huggies Tripla Protecao ou MamyPoko', 'available', 60),
  ('M21', (select id from categories where name = 'Fralda M'), 'Fralda M + Condicionador Baby Dove', 85, 'Pampers Confort Sec, Huggies Tripla Protecao ou MamyPoko', 'available', 61),
  ('M22', (select id from categories where name = 'Fralda M'), 'Fralda M + Colônia Natura Mamãe e Bebê', 125, 'Pampers Confort Sec, Huggies Tripla Protecao ou MamyPoko', 'available', 62),
  ('M23', (select id from categories where name = 'Fralda M'), 'Fralda M + Colônia Natura Mamãe e Bebê', 125, 'Pampers Confort Sec, Huggies Tripla Protecao ou MamyPoko', 'available', 63),
  ('M24', (select id from categories where name = 'Fralda M'), 'Fralda M + Colônia Natura Mamãe e Bebê', 125, 'Pampers Confort Sec, Huggies Tripla Protecao ou MamyPoko', 'available', 64),
  ('M25', (select id from categories where name = 'Fralda M'), 'Fralda M + Algodão Cremer', 70, 'Pampers Confort Sec, Huggies Tripla Protecao ou MamyPoko', 'available', 65),
  ('M26', (select id from categories where name = 'Fralda M'), 'Fralda M + Algodão Cremer', 70, 'Pampers Confort Sec, Huggies Tripla Protecao ou MamyPoko', 'available', 66),
  ('M27', (select id from categories where name = 'Fralda M'), 'Fralda M + Algodão Cremer', 70, 'Pampers Confort Sec, Huggies Tripla Protecao ou MamyPoko', 'available', 67),
  ('M28', (select id from categories where name = 'Fralda M'), 'Fralda M + Cotonetes Johnson''s Baby', 70, 'Pampers Confort Sec, Huggies Tripla Protecao ou MamyPoko', 'available', 68),
  ('M29', (select id from categories where name = 'Fralda M'), 'Fralda M + Cotonetes Johnson''s Baby', 70, 'Pampers Confort Sec, Huggies Tripla Protecao ou MamyPoko', 'available', 69),
  ('M30', (select id from categories where name = 'Fralda M'), 'Fralda M + Cotonetes Johnson''s Baby', 70, 'Pampers Confort Sec, Huggies Tripla Protecao ou MamyPoko', 'available', 70),
  ('M31', (select id from categories where name = 'Fralda M'), 'Fralda M + Prendedor de Chupeta Buba', 85, 'Pampers Confort Sec, Huggies Tripla Protecao ou MamyPoko', 'available', 71),
  ('M32', (select id from categories where name = 'Fralda M'), 'Fralda M + Prendedor de Chupeta Buba', 85, 'Pampers Confort Sec, Huggies Tripla Protecao ou MamyPoko', 'available', 72),
  ('M33', (select id from categories where name = 'Fralda M'), 'Fralda M + Prendedor de Chupeta Buba', 85, 'Pampers Confort Sec, Huggies Tripla Protecao ou MamyPoko', 'available', 73),
  ('M34', (select id from categories where name = 'Fralda M'), 'Fralda M + Mimo', 95, 'Pampers Confort Sec, Huggies Tripla Protecao ou MamyPoko', 'available', 74),
  ('M35', (select id from categories where name = 'Fralda M'), 'Fralda M + Mimo', 95, 'Pampers Confort Sec, Huggies Tripla Protecao ou MamyPoko', 'available', 75),
  ('M36', (select id from categories where name = 'Fralda M'), 'Fralda M + Mimo', 95, 'Pampers Confort Sec, Huggies Tripla Protecao ou MamyPoko', 'available', 76),
  ('M37', (select id from categories where name = 'Fralda M'), 'Fralda M + Mimo', 95, 'Pampers Confort Sec, Huggies Tripla Protecao ou MamyPoko', 'available', 77),
  ('M38', (select id from categories where name = 'Fralda M'), 'Fralda M + Mimo', 95, 'Pampers Confort Sec, Huggies Tripla Protecao ou MamyPoko', 'available', 78),
  ('M39', (select id from categories where name = 'Fralda M'), 'Fralda M + Mimo', 95, 'Pampers Confort Sec, Huggies Tripla Protecao ou MamyPoko', 'available', 79),
  ('M40', (select id from categories where name = 'Fralda M'), 'Fralda M + Lenço Umedecido Huggies', 75, 'Pampers Confort Sec, Huggies Tripla Protecao ou MamyPoko', 'available', 80),
  ('M41', (select id from categories where name = 'Fralda M'), 'Fralda M + Pomada Bepantriz Baby', 85, 'Pampers Confort Sec, Huggies Tripla Protecao ou MamyPoko', 'available', 81),
  ('M42', (select id from categories where name = 'Fralda M'), 'Fralda M + Shampoo Baby Dove', 85, 'Pampers Confort Sec, Huggies Tripla Protecao ou MamyPoko', 'available', 82),
  ('M43', (select id from categories where name = 'Fralda M'), 'Fralda M + Condicionador Baby Dove', 85, 'Pampers Confort Sec, Huggies Tripla Protecao ou MamyPoko', 'available', 83),
  ('M44', (select id from categories where name = 'Fralda M'), 'Fralda M + Colônia Natura Mamãe e Bebê', 125, 'Pampers Confort Sec, Huggies Tripla Protecao ou MamyPoko', 'available', 84),
  ('M45', (select id from categories where name = 'Fralda M'), 'Fralda M + Algodão Cremer', 70, 'Pampers Confort Sec, Huggies Tripla Protecao ou MamyPoko', 'available', 85),
  ('M46', (select id from categories where name = 'Fralda M'), 'Fralda M + Cotonetes Johnson''s Baby', 70, 'Pampers Confort Sec, Huggies Tripla Protecao ou MamyPoko', 'available', 86),
  ('M47', (select id from categories where name = 'Fralda M'), 'Fralda M + Prendedor de Chupeta Buba', 85, 'Pampers Confort Sec, Huggies Tripla Protecao ou MamyPoko', 'available', 87),
  ('M48', (select id from categories where name = 'Fralda M'), 'Fralda M + Mimo', 95, 'Pampers Confort Sec, Huggies Tripla Protecao ou MamyPoko', 'available', 88),
  ('M49', (select id from categories where name = 'Fralda M'), 'Fralda M + Mimo', 95, 'Pampers Confort Sec, Huggies Tripla Protecao ou MamyPoko', 'available', 89),
  ('M50', (select id from categories where name = 'Fralda M'), 'Fralda M + Lenço Umedecido Huggies', 75, 'Pampers Confort Sec, Huggies Tripla Protecao ou MamyPoko', 'available', 90),
  ('M51', (select id from categories where name = 'Fralda M'), 'Fralda M + Pomada Bepantriz Baby', 85, 'Pampers Confort Sec, Huggies Tripla Protecao ou MamyPoko', 'available', 91),
  ('M52', (select id from categories where name = 'Fralda M'), 'Fralda M + Shampoo Baby Dove', 85, 'Pampers Confort Sec, Huggies Tripla Protecao ou MamyPoko', 'available', 92),
  ('M53', (select id from categories where name = 'Fralda M'), 'Fralda M + Condicionador Baby Dove', 85, 'Pampers Confort Sec, Huggies Tripla Protecao ou MamyPoko', 'available', 93),
  ('M54', (select id from categories where name = 'Fralda M'), 'Fralda M + Colônia Natura Mamãe e Bebê', 125, 'Pampers Confort Sec, Huggies Tripla Protecao ou MamyPoko', 'available', 94),
  ('M55', (select id from categories where name = 'Fralda M'), 'Fralda M + Algodão Cremer', 70, 'Pampers Confort Sec, Huggies Tripla Protecao ou MamyPoko', 'available', 95),
  ('G1', (select id from categories where name = 'Fralda G'), 'Fralda G + Lenço Umedecido Huggies', 80, 'Pampers Confort Sec, Huggies Tripla Protecao ou MamyPoko', 'available', 96),
  ('G2', (select id from categories where name = 'Fralda G'), 'Fralda G + Lenço Umedecido Huggies', 80, 'Pampers Confort Sec, Huggies Tripla Protecao ou MamyPoko', 'available', 97),
  ('G3', (select id from categories where name = 'Fralda G'), 'Fralda G + Pomada Bepantriz Baby', 90, 'Pampers Confort Sec, Huggies Tripla Protecao ou MamyPoko', 'available', 98),
  ('G4', (select id from categories where name = 'Fralda G'), 'Fralda G + Pomada Bepantriz Baby', 90, 'Pampers Confort Sec, Huggies Tripla Protecao ou MamyPoko', 'available', 99),
  ('G5', (select id from categories where name = 'Fralda G'), 'Fralda G + Sabonete Natura Mamãe e Bebê', 105, 'Pampers Confort Sec, Huggies Tripla Protecao ou MamyPoko', 'available', 100),
  ('G6', (select id from categories where name = 'Fralda G'), 'Fralda G + Sabonete Natura Mamãe e Bebê', 105, 'Pampers Confort Sec, Huggies Tripla Protecao ou MamyPoko', 'available', 101),
  ('G7', (select id from categories where name = 'Fralda G'), 'Fralda G + Shampoo Baby Dove', 90, 'Pampers Confort Sec, Huggies Tripla Protecao ou MamyPoko', 'available', 102),
  ('G8', (select id from categories where name = 'Fralda G'), 'Fralda G + Shampoo Baby Dove', 90, 'Pampers Confort Sec, Huggies Tripla Protecao ou MamyPoko', 'available', 103),
  ('G9', (select id from categories where name = 'Fralda G'), 'Fralda G + Condicionador Baby Dove', 90, 'Pampers Confort Sec, Huggies Tripla Protecao ou MamyPoko', 'available', 104),
  ('G10', (select id from categories where name = 'Fralda G'), 'Fralda G + Condicionador Baby Dove', 90, 'Pampers Confort Sec, Huggies Tripla Protecao ou MamyPoko', 'available', 105),
  ('G11', (select id from categories where name = 'Fralda G'), 'Fralda G + Colônia Natura Mamãe e Bebê', 130, 'Pampers Confort Sec, Huggies Tripla Protecao ou MamyPoko', 'available', 106),
  ('G12', (select id from categories where name = 'Fralda G'), 'Fralda G + Colônia Natura Mamãe e Bebê', 130, 'Pampers Confort Sec, Huggies Tripla Protecao ou MamyPoko', 'available', 107),
  ('G13', (select id from categories where name = 'Fralda G'), 'Fralda G + Algodão Cremer', 75, 'Pampers Confort Sec, Huggies Tripla Protecao ou MamyPoko', 'available', 108),
  ('G14', (select id from categories where name = 'Fralda G'), 'Fralda G + Algodão Cremer', 75, 'Pampers Confort Sec, Huggies Tripla Protecao ou MamyPoko', 'available', 109),
  ('G15', (select id from categories where name = 'Fralda G'), 'Fralda G + Cotonetes Johnson''s Baby', 75, 'Pampers Confort Sec, Huggies Tripla Protecao ou MamyPoko', 'available', 110),
  ('G16', (select id from categories where name = 'Fralda G'), 'Fralda G + Cotonetes Johnson''s Baby', 75, 'Pampers Confort Sec, Huggies Tripla Protecao ou MamyPoko', 'available', 111),
  ('G17', (select id from categories where name = 'Fralda G'), 'Fralda G + Prendedor de Chupeta Buba', 90, 'Pampers Confort Sec, Huggies Tripla Protecao ou MamyPoko', 'available', 112),
  ('G18', (select id from categories where name = 'Fralda G'), 'Fralda G + Prendedor de Chupeta Buba', 90, 'Pampers Confort Sec, Huggies Tripla Protecao ou MamyPoko', 'available', 113),
  ('G19', (select id from categories where name = 'Fralda G'), 'Fralda G + Lenço Umedecido Huggies', 80, 'Pampers Confort Sec, Huggies Tripla Protecao ou MamyPoko', 'available', 114),
  ('G20', (select id from categories where name = 'Fralda G'), 'Fralda G + Pomada Bepantriz Baby', 90, 'Pampers Confort Sec, Huggies Tripla Protecao ou MamyPoko', 'available', 115)
on conflict (seed_code) do update set
  category_id = excluded.category_id,
  name = excluded.name,
  estimated_value = excluded.estimated_value,
  suggested_brands = excluded.suggested_brands,
  sort_order = excluded.sort_order;
